### PR TITLE
Check for proxy container if kube-proxy is not present

### LINKED ISSUE #314: Check for `proxy` container if `kube-proxy` is not present
**What happened**:
Rules that check the `kube-proxy` pods depend on the pods having a `kube-proxy` container. Ex.:
https://github.com/gardener/diki/blob/1529d1bbbc1a195da4adac46561b427c5a65145d/pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400.go#L205

I would like that in all instances where we search for the `kube-proxy` container to check for `proxy` container if the former is not present

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by georgibaltiev**
**What this PR does / why we need it**:
This PR modifies the GetContainerCommand and GetContainerID util functions to be variadic and accept more than one possible container name for matching. Along with those modifications, rules that utilize the functions (242400, 242447, 242448) are also modified to search for "proxy" containers if "kube-proxy" containers are absent. Additional unit tests are added to validate the new modification.

**Which issue(s) this PR fixes**:
Fixes #314 

**Special notes for your reviewer**:
NONE

**Release note**:

```bugfix user
A bug causing DISA Kubernetes STIG rules that check the `kube-proxy` container to fail to find the container, when the container name is `proxy`, was fixed.
```

### CODE REVIEW

File: pkg/internal/utils/utils.go [hunk 1]
```diff
@@ -164,24 +164,27 @@ func GetMountedFilesStats(
...
+		switch {
+		case len(containerID) == 0:
+			return "", fmt.Errorf("container with name %s not (yet) running", containerName)
+		case strings.HasPrefix(containerID, "containerd://"):
+			return strings.Split(containerID, "//")[1], nil
+		default:
+			return "", fmt.Errorf("cannot handle container with name %s", containerName)
+		}
 	}
+	return "", fmt.Errorf("container with any of the specified names in the list %s not (yet) in status", containerNames)
```
Comment (AleksandarSavchev) [inline pkg/internal/utils/utils.go:187]:
```suggestion
	return "", fmt.Errorf("container with name in %v not (yet) in status", containerNames)
```

File: pkg/kubernetes/utils/utils.go [hunk 2]
```diff
@@ -401,12 +401,24 @@ func GetKubeletCommand(ctx context.Context, podExecutor pod.PodExecutor) (string
...
+			break
+		}
 	}
 
+	if !found {
+		return "", fmt.Errorf("pod does not contain any of the containers specified in the provided list: %s", containerNames)
+	}
 	rawCommand := strings.Join(append(container.Command, container.Args...), " ")
 	return rawCommand, nil
 }
```
Comment (AleksandarSavchev) [inline pkg/kubernetes/utils/utils.go:424]:
```suggestion
// The first container name that exists in the Pod is selected
func GetContainerCommand(pod corev1.Pod, containerNames ...string) (string, error) {
	for _, containerName := range containerNames {
		if container, found := GetContainerFromPod(&pod, containerName); found {
			rawCommand := strings.Join(append(container.Command, container.Args...), " ")
			return rawCommand, nil
		}
	}

	return "", fmt.Errorf("pod does not contain container with name in %v", containerNames)
}
```
Let's make the function simpler while keeping the same functionality.

File: pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go [hunk 3]
```diff
@@ -54,11 +54,11 @@ func (r *Rule242400) Name() string {
...
-		checkResults      []rule.CheckResult
-		deploymentNames   = []string{"kube-apiserver", "kube-controller-manager", "kube-scheduler"}
-		shootTarget       = rule.NewTarget("cluster", "shoot")
-		seedTarget        = rule.NewTarget("cluster", "seed")
-		kubeProxySelector = labels.SelectorFromSet(labels.Set{"role": "proxy"})
+		checkResults    []rule.CheckResult
+		deploymentNames = []string{"kube-apiserver", "kube-controller-manager", "kube-scheduler"}
+		shootTarget     = rule.NewTarget("cluster", "shoot")
+		seedTarget      = rule.NewTarget("cluster", "seed")
+		proxySelector   = labels.SelectorFromSet(labels.Set{"role": "proxy"})
```
Comment (AleksandarSavchev) [inline pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go:61]:
```suggestion
		kubeProxySelector = labels.SelectorFromSet(labels.Set{"role": "proxy"})
```
Please keep the old name for this selector as it is more specific.

File: pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go [hunk 4]
```diff
@@ -187,10 +187,11 @@ func (r *Rule242400) checkKubeProxy(
...
 	var (
-		checkResults     []rule.CheckResult
-		additionalLabels = map[string]string{pod.LabelInstanceID: r.InstanceID}
-		podName          = fmt.Sprintf("diki-%s-%s", r.ID(), sharedrules.Generator.Generate(10))
-		execPodTarget    = rule.NewTarget("cluster", "shoot", "name", podName, "namespace", "kube-system", "kind", "pod")
+		checkResults            []rule.CheckResult
+		additionalLabels        = map[string]string{pod.LabelInstanceID: r.InstanceID}
+		podName                 = fmt.Sprintf("diki-%s-%s", r.ID(), sharedrules.Generator.Generate(10))
+		execPodTarget           = rule.NewTarget("cluster", "shoot", "name", podName, "namespace", "kube-system", "kind", "pod")
+		kubeProxyContainerNames = []string{"kube-proxy"}
```
Comment (AleksandarSavchev) [inline pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go:194]:
```suggestion
		kubeProxyContainerNames = "kube-proxy"
```
There is no need to use a slice here.

File: pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go [hunk 5]
```diff
@@ -228,7 +229,7 @@ func (r *Rule242400) checkKubeProxy(
 	for _, pod := range pods {
 		podTarget := rule.NewTarget("cluster", "shoot", "name", pod.Name, "namespace", pod.Namespace, "kind", "pod")
 
-		rawKubeProxyCommand, err := kubeutils.GetContainerCommand(pod, "kube-proxy")
+		rawKubeProxyCommand, err := kubeutils.GetContainerCommand(pod, kubeProxyContainerNames...)
```
Comment (AleksandarSavchev) [inline pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go:232]:
```suggestion
		rawKubeProxyCommand, err := kubeutils.GetContainerCommand(pod, kubeProxyContainerNames)
```
After changing kubeProxyContainerNames to a `string`

File: pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go [hunk 6]
```diff
@@ -248,7 +249,7 @@ func (r *Rule242400) checkKubeProxy(
 
 		var allAlpha *bool
 		if len(configPath) != 0 {
-			kubeProxyContainerID, err := intutils.GetContainerID(pod, "kube-proxy")
+			kubeProxyContainerID, err := intutils.GetContainerID(pod, kubeProxyContainerNames...)
```
Comment (AleksandarSavchev) [inline pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go:252]:
```suggestion
			kubeProxyContainerID, err := intutils.GetContainerID(pod, kubeProxyContainerNames)
```

File: pkg/provider/gardener/ruleset/disak8sstig/rules/242400_test.go [hunk 7]
```diff
@@ -147,6 +147,10 @@ var _ = Describe("#242400", func() {
 			},
 		}
 
+		plainProxyPod := plainPod.DeepCopy()
+		plainProxyPod.Status.ContainerStatuses[0].Name = "proxy"
+		plainProxyPod.Status.ContainerStatuses[0].ContainerID = "containerd://foo"
+
```
Comment (AleksandarSavchev) [inline pkg/provider/gardener/ruleset/disak8sstig/rules/242400_test.go:153]:
```suggestion
```
`plainProxyPod` has been declared here but it is not in use. There is not need to modify these unit test.

File: pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400.go [hunk 8]
```diff
@@ -202,9 +203,9 @@ func (r *Rule242400) checkKubeProxy(
 	for _, pod := range pods {
 		podTarget := rule.NewTarget("name", pod.Name, "namespace", pod.Namespace, "kind", "pod")
 
-		rawKubeProxyCommand, err := kubeutils.GetContainerCommand(pod, "kube-proxy")
+		rawKubeProxyCommand, err := kubeutils.GetContainerCommand(pod, kubeProxyContainerNames...)
 		if err != nil {
-			checkResults = append(checkResults, rule.ErroredCheckResult(err.Error(), podTarget))
+			checkResults = append(checkResults, rule.ErroredCheckResult("Failed to find any containers appropriate for evaluation", podTarget.With("details", err.Error())))
```
Comment (AleksandarSavchev) [inline pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400.go:208]:
```suggestion
			checkResults = append(checkResults, rule.ErroredCheckResult(err.Error(), podTarget))
```
The error from `kubeutils.GetContainerCommand`. Note: we normally do not add error message in target `details`

File: pkg/shared/ruleset/disak8sstig/rules/242447.go [hunk 9]
```diff
@@ -137,9 +138,9 @@ func (r *Rule242447) Run(ctx context.Context) (rule.RuleResult, error) {
 			expectedFilePermissionsMax := "644"
 			podTarget := target.With("name", pod.Name, "namespace", pod.Namespace, "kind", "pod")
 
-			rawKubeProxyCommand, err := kubeutils.GetContainerCommand(pod, "kube-proxy")
+			rawKubeProxyCommand, err := kubeutils.GetContainerCommand(pod, kubeProxyContainerNames...)
 			if err != nil {
-				checkResults = append(checkResults, rule.ErroredCheckResult(err.Error(), podTarget))
+				checkResults = append(checkResults, rule.ErroredCheckResult("Failed to find any containers appropriate for evaluation", podTarget.With("details", err.Error())))
```
Comment (AleksandarSavchev) [inline pkg/shared/ruleset/disak8sstig/rules/242447.go:143]:
```suggestion
				checkResults = append(checkResults, rule.ErroredCheckResult(err.Error(), podTarget))
```
Same as above

File: pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400_test.go [hunk 10]
```diff
@@ -292,6 +292,69 @@ var _ = Describe("#242400", func() {
...
+		}
+
+		ruleResult, err := r.Run(ctx)
+		Expect(err).To(BeNil())
+
+		expectedResults := []rule.CheckResult{
+			rule.PassedCheckResult("Option featureGates.AllAlpha set to allowed value.", rule.NewTarget("kind", "node", "name", "node1")),
+			rule.PassedCheckResult("Option featureGates.AllAlpha not set.", rule.NewTarget("name", kubeProxyContainerPod.Name, "namespace", kubeProxyContainerPod.Namespace, "kind", "pod")),
+			rule.ErroredCheckResult("Failed to find any containers appropriate for evaluation", rule.NewTarget("name", nonValidContainerPod.Name, "namespace", nonValidContainerPod.Namespace, "kind", "pod", "details", "pod does not contain any of the containers specified in the provided list: [kube-proxy proxy]")),
+			rule.FailedCheckResult("Option featureGates.AllAlpha set to not allowed value.", rule.NewTarget("name", proxyContainerPod.Name, "namespace", proxyContainerPod.Namespace, "kind", "pod")),
```
Comment (AleksandarSavchev) [inline pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400_test.go:352]:
```suggestion
			rule.PassedCheckResult("Option featureGates.AllAlpha not set.", rule.NewTarget("name", "kube-proxy-container-pod", "namespace", "kube-system", "kind", "pod")),
			rule.ErroredCheckResult("Failed to find any containers appropriate for evaluation", rule.NewTarget("name", "non-valid-container-pod", "namespace", "kube-system", "kind", "pod", "details", "pod does not contain any of the containers specified in the provided list: [kube-proxy proxy]")),
			rule.FailedCheckResult("Option featureGates.AllAlpha set to not allowed value.", rule.NewTarget("name", "proxy-container-pod", "namespace", "kube-system", "kind", "pod")),
```

For unit tests it is better to hard code the expected results. Hardcoding the expected results would show if a variable has changed.

File: pkg/shared/ruleset/disak8sstig/rules/242447_test.go [hunk 11]
```diff
@@ -166,6 +166,56 @@ var _ = Describe("#242447", func() {
...
+			rule.PassedCheckResult("File has expected permissions", rule.NewTarget("name", kubeProxyContainerPod.Name, "namespace", kubeProxyContainerPod.Namespace, "kind", "pod", "details", "fileName: /var/lib/kubeconfig, permissions: 600")),
+			rule.ErroredCheckResult("Failed to find any containers appropriate for evaluation", rule.NewTarget("name", nonValidContainerPod.Name, "namespace", nonValidContainerPod.Namespace, "kind", "pod", "details", "pod does not contain any of the containers specified in the provided list: [kube-proxy proxy]")),
+			rule.FailedCheckResult("File has too wide permissions", rule.NewTarget("name", proxyContainerPod.Name, "namespace", proxyContainerPod.Namespace, "kind", "pod", "details", "fileName: /var/lib/config, permissions: 664, expectedPermissionsMax: 644")),
+			rule.FailedCheckResult("File has too wide permissions", rule.NewTarget("name", proxyContainerPod.Name, "namespace", proxyContainerPod.Namespace, "kind", "pod", "details", "fileName: /var/lib/kubeconfig2, permissions: 606, expectedPermissionsMax: 644")),
```
Comment (AleksandarSavchev) [inline pkg/shared/ruleset/disak8sstig/rules/242447_test.go:213]: Hardcode the variables here as well.

File: pkg/shared/ruleset/disak8sstig/rules/242448.go [hunk 12]
```diff
@@ -153,9 +154,9 @@ func (r *Rule242448) Run(ctx context.Context) (rule.RuleResult, error) {
 			selectedFileStats := []intutils.FileStats{}
 			podTarget := target.With("name", pod.Name, "namespace", pod.Namespace, "kind", "pod")
 
-			rawKubeProxyCommand, err := kubeutils.GetContainerCommand(pod, "kube-proxy")
+			rawKubeProxyCommand, err := kubeutils.GetContainerCommand(pod, kubeProxyContainerNames...)
 			if err != nil {
-				checkResults = append(checkResults, rule.ErroredCheckResult(err.Error(), podTarget))
+				checkResults = append(checkResults, rule.ErroredCheckResult("Failed to find any containers appropriate for evaluation", podTarget.With("details", err.Error())))
```
Comment (AleksandarSavchev) [inline pkg/shared/ruleset/disak8sstig/rules/242448.go:159]:
```suggestion
				checkResults = append(checkResults, rule.ErroredCheckResult(err.Error(), podTarget))
```

File: pkg/shared/ruleset/disak8sstig/rules/242448_test.go [hunk 13]
```diff
@@ -167,6 +167,56 @@ var _ = Describe("#242448", func() {
...
+			rule.PassedCheckResult("File has expected owners", rule.NewTarget("name", kubeProxyContainerPod.Name, "namespace", kubeProxyContainerPod.Namespace, "kind", "pod", "details", "fileName: /var/lib/kubeconfig, ownerUser: 0, ownerGroup: 0")),
+			rule.ErroredCheckResult("Failed to find any containers appropriate for evaluation", rule.NewTarget("name", nonValidContainerPod.Name, "namespace", nonValidContainerPod.Namespace, "kind", "pod", "details", "pod does not contain any of the containers specified in the provided list: [kube-proxy proxy]")),
+			rule.FailedCheckResult("File has unexpected owner user", rule.NewTarget("name", proxyContainerPod.Name, "namespace", proxyContainerPod.Namespace, "kind", "pod", "details", "fileName: /var/lib/config, ownerUser: 1000, expectedOwnerUsers: [0]")),
+			rule.FailedCheckResult("File has unexpected owner group", rule.NewTarget("name", proxyContainerPod.Name, "namespace", proxyContainerPod.Namespace, "kind", "pod", "details", "fileName: /var/lib/kubeconfig2, ownerGroup: 1000, expectedOwnerGroups: [0]")),
```
Comment (AleksandarSavchev) [inline pkg/shared/ruleset/disak8sstig/rules/242448_test.go:214]: Hardcode these as well.

File: pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400_test.go [hunk 14]
```diff
@@ -292,6 +292,69 @@ var _ = Describe("#242400", func() {
 		Expect(ruleResult.CheckResults).To(ConsistOf(expectedCheckResults))
 	})
 
+	It("should correctly look up for a proxy container if the kube-proxy container is absent", func() {
```
Comment (AleksandarSavchev) [inline pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400_test.go:295]:
```suggestion
	It("should correctly find the kube-proxy container", func() {
```

File: pkg/shared/ruleset/disak8sstig/rules/242447_test.go [hunk 15]
```diff
@@ -166,6 +166,56 @@ var _ = Describe("#242447", func() {
 		}))
 	})
 
+	It("should correctly look up for a proxy container if the kube-proxy container is absent", func() {
```
Comment (AleksandarSavchev) [inline pkg/shared/ruleset/disak8sstig/rules/242447_test.go:169]:
```suggestion
	It("should correctly find the kube-proxy container", func() {
```

File: pkg/shared/ruleset/disak8sstig/rules/242448_test.go [hunk 16]
```diff
@@ -167,6 +167,56 @@ var _ = Describe("#242448", func() {
 		}))
 	})
 
+	It("should correctly look up for a proxy container if the kube-proxy container is absent", func() {
```
Comment (AleksandarSavchev) [inline pkg/shared/ruleset/disak8sstig/rules/242448_test.go:170]:
```suggestion
	It("should correctly find the kube-proxy container", func() {
```

**Review by AleksandarSavchev — CHANGES_REQUESTED** [review]

File: pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go [hunk 17]
```diff
@@ -187,10 +187,11 @@ func (r *Rule242400) checkKubeProxy(
...
 	var (
-		checkResults     []rule.CheckResult
-		additionalLabels = map[string]string{pod.LabelInstanceID: r.InstanceID}
-		podName          = fmt.Sprintf("diki-%s-%s", r.ID(), sharedrules.Generator.Generate(10))
-		execPodTarget    = rule.NewTarget("cluster", "shoot", "name", podName, "namespace", "kube-system", "kind", "pod")
+		checkResults            []rule.CheckResult
+		additionalLabels        = map[string]string{pod.LabelInstanceID: r.InstanceID}
+		podName                 = fmt.Sprintf("diki-%s-%s", r.ID(), sharedrules.Generator.Generate(10))
+		execPodTarget           = rule.NewTarget("cluster", "shoot", "name", podName, "namespace", "kube-system", "kind", "pod")
+		kubeProxyContainerNames = "kube-proxy"
```
Comment (AleksandarSavchev) [inline pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go:194]:
```suggestion
		kubeProxyContainerName = "kube-proxy"
```

File: pkg/internal/utils/utils.go [hunk 18]
```diff
@@ -164,24 +164,27 @@ func GetMountedFilesStats(
 }
 
 // GetContainerID returns the container ID specified in the container statust by container name
```
[the remark this answers is not in the document]
Comment (AleksandarSavchev) [reply pkg/internal/utils/utils.go]: Please add the full comment.

File: pkg/kubernetes/utils/utils.go (hunk 2 above)
Comment (AleksandarSavchev) [reply pkg/kubernetes/utils/utils.go]: Please use the suggestion. The full comment is missing, the `if` clause can be on the line where the variables are declared and the error message is different.

**Review by AleksandarSavchev — CHANGES_REQUESTED** [review]
Looks good, just a few nits from last review and a new one

**Review by AleksandarSavchev — APPROVED** [review]
/lgtm
/cc @dimityrmirchev
