### PR TITLE
Configure rule options for rules 2000 of the Security Hardened Shoot Cluster ruleset and 242390 of the DISA STIG ruleset

### LINKED ISSUE #541: Allow exceptions for specific endpoint paths in rules that check for enabled Anonymous Authentication
**What would you like to be added**:

Currently, rules that check for an enabled anonymous authentication on the kube-apiserver evaluate the `AuthenticationConfiguration` resource, and fail if the `anonymous.enabled` flag is set to `true`, regardless of whether any allowed paths are specified or not. 

The user should be able to configure rule options, with which to accept certain paths on which anonymous traffic could be allowed. 

An example ruleOption for rule 242390 could look like the following example:
```yaml
ruleOptions: 
- ruleID: "242390"
  allowedPaths:
  - name: /healthz
  - name: /livez
```

Rules that need to be modified:
- [ ] rule 242390 of the DISA STIG ruleset
- [ ] rule 2000 of the Security Hardened Shoot Cluster ruleset

**Why is this needed**:
To improve stakeholder experience.

### PR DESCRIPTION
**Pull request by georgibaltiev**
**What this PR does / why we need it**:

Diki supports two rules that check for enabled anonymous authentication to the `kube-apiserver`:

- Rule 242390 of the `DISA STIG` ruleset
- Rule 2000 of the `Security Hardened Shoot Cluster` ruleset

Currently, these rules check the `kube-apiserver`'s `AuthenticationConfiguration`. If the the `.anonymous.enabled` field is set to true, Diki returns a `Failed` checkResult, regardless of whether condition endpoints are present in the configuration. In order to perform more precise checks, `ruleOptions` should be introduced to allow anonymous authentication to specific endpoints.

For both rules, this PR configures `ruleOptions`, which represent a list of allowed endpoints. If the `kube-apiserver`'s `AuthenticationConfiguration` contains a subset of the allowed endpoints, Diki returns an `Accepted` check result. 
All other endpoints, which are not present in the `ruleOptions` will be returned as `Failed` checkResults.

Users can add `ruleOptions` in their configuration files via the following way:
```yaml
ruleOptions:
 - ruleID: ("242390"|"2000")
   args:
     acceptedEndpoints:
     - path: /healthz
     - path: /livez
```

**Which issue(s) this PR fixes**:
Fixes #541 

**Special notes for your reviewer**:
The `Managed Kubernetes`-specific implementation of DISA rule 242390 does not have options configured, since the rule is not able to perform any checks on the `AuthenticationConfguration` resource. 

**Release note**:

```feature user
Rules 242390 of the DISA STIG ruleset and 2000 of the Security Hardened Shoot Cluster ruleset now support options to exempt specific endpoints from disabling their anonymous authentication.
```

### CODE REVIEW

File: pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go [hunk 1]
```diff
@@ -7,27 +7,59 @@ package rules
...
+
+func (o Options2000) Validate() field.ErrorList {
+	var (
+		allErrs              field.ErrorList
+		allowedEndpointsPath = field.NewPath("allowedEndpoints")
+	)
+
+	if len(o.AllowedEndpoints) == 0 {
+		return field.ErrorList{field.Required(allowedEndpointsPath, "must not be empty")}
+	}
```
Comment (dimityrmirchev) [inline pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go:54]: Why is this required? What if I do not want to allow any endpoints?

File: pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go [hunk 2]
```diff
@@ -7,27 +7,59 @@ package rules
...
+
+type Options2000 struct {
+	AllowedEndpoints []AllowedEndpoint `yaml:"allowedEndpoints" json:"allowedEndpoints"`
+}
+
+type AllowedEndpoint struct {
+	Path string `yaml:"path" json:"path"`
+}
+
+func (o Options2000) Validate() field.ErrorList {
```
Comment (dimityrmirchev) [inline pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go:46]:
```suggestion
func (o *Options2000) Validate() field.ErrorList {
```

File: pkg/shared/ruleset/disak8sstig/rules/242390.go [hunk 3]
```diff
@@ -116,7 +148,26 @@ func (r *Rule242390) Run(ctx context.Context) (rule.RuleResult, error) {
 	case authConfig.Anonymous == nil:
 		return rule.Result(r, rule.FailedCheckResult("The authentication configuration does not explicitly disable anonymous authentication.", target)), nil
 	case authConfig.Anonymous != nil && authConfig.Anonymous.Enabled:
-		return rule.Result(r, rule.FailedCheckResult("The authentication configuration has anonymous authentication enabled.", target)), nil
+
+		if r.Options == nil || len(authConfig.Anonymous.Conditions) == 0 {
```
Comment (dimityrmirchev) [inline pkg/shared/ruleset/disak8sstig/rules/242390.go:152]:
```suggestion
		if r.Options == nil || len(authConfig.Anonymous.Conditions) == 0 {
```

File: pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go [hunk 4]
```diff
@@ -89,7 +121,24 @@ func (r *Rule2000) Run(ctx context.Context) (rule.RuleResult, error) {
...
+			if !slices.ContainsFunc(r.Options.AllowedEndpoints, func(allowedPath AllowedEndpoint) bool {
+				return allowedPath.Path == condition.Path
+			}) {
+				checkResults = append(checkResults, rule.FailedCheckResult(fmt.Sprintf("Anonymous authentication is not allowed for endpoint %s of the kube-apiserver.", condition.Path), configMapTarget))
+			}
+		}
+
+		if len(checkResults) == 0 {
+			return rule.Result(r, rule.AcceptedCheckResult("Anonymous authentication is allowed for the specified endpoints of the kube-apiserver.", configMapTarget)), nil
+		}
```
Comment (dimityrmirchev) [inline pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go:140]: Shouldn't we instead add an accepted check for each allowed endpoint?

File: example/config/garden.yaml [hunk 5]
```diff
@@ -37,6 +37,11 @@ providers:       # contains information about known providers
     #     - KubeSystem
     #     - Cluster
     # - ruleID: "2000"
+    #   args:
+    #     allowedEndpoints:
```
Comment (dimityrmirchev) [inline example/config/garden.yaml:41]: I am wondering if this should be called "allowed" or "accepted". What is the convention that are we using so far? @AleksandarSavchev any opinions?

File: pkg/shared/ruleset/disak8sstig/rules/242390.go [hunk 6]
```diff
@@ -7,27 +7,59 @@ package rules
...
+
+type Options242390 struct {
+	AllowedEndpoints []AllowedEndpoint `yaml:"allowedEndpoints" json:"allowedEndpoints"`
+}
+
+type AllowedEndpoint struct {
+	Path string `yaml:"path" json:"path"`
+}
+
+func (o Options242390) Validate() field.ErrorList {
```
Comment (dimityrmirchev) [inline pkg/shared/ruleset/disak8sstig/rules/242390.go:46]:
```suggestion
func (o *Options242390) Validate() field.ErrorList {
```

**Review by dimityrmirchev — COMMENTED** [review]
Thank you! I few comments/suggestions

File: pkg/provider/gardener/ruleset/disak8sstig/v2r2_ruleset.go [hunk 7]
```diff
@@ -76,6 +76,10 @@ func (r *Ruleset) registerV2R2Rules(ruleOptions map[string]config.RuleOptionsCon
 		return err
 	}
 
+	opts242390, err := getV2R2OptionOrNil[sharedrules.Options242390](ruleOptions[sharedrules.ID242390].Args)
+	if err != nil {
+		return fmt.Errorf("rule option 242445 error: %s", err.Error())
```
Comment (AleksandarSavchev) [inline pkg/provider/gardener/ruleset/disak8sstig/v2r2_ruleset.go:81]:
```suggestion
		return fmt.Errorf("rule option 242390 error: %s", err.Error())
```

File: pkg/provider/gardener/ruleset/disak8sstig/v2r3_ruleset.go [hunk 8]
```diff
@@ -76,6 +76,10 @@ func (r *Ruleset) registerV2R3Rules(ruleOptions map[string]config.RuleOptionsCon
 		return err
 	}
 
+	opts242390, err := getV2R2OptionOrNil[sharedrules.Options242390](ruleOptions[sharedrules.ID242390].Args)
+	if err != nil {
+		return fmt.Errorf("rule option 242445 error: %s", err.Error())
```
Comment (AleksandarSavchev) [inline pkg/provider/gardener/ruleset/disak8sstig/v2r3_ruleset.go:81]:
```suggestion
		return fmt.Errorf("rule option 242390 error: %s", err.Error())
```

File: pkg/provider/virtualgarden/ruleset/disak8sstig/v2r2_ruleset.go [hunk 9]
```diff
@@ -31,6 +31,10 @@ func (r *Ruleset) registerV2R2Rules(ruleOptions map[string]config.RuleOptionsCon
 	if err != nil {
 		return err
 	}
+	opts242390, err := getV2R2OptionOrNil[sharedrules.Options242390](ruleOptions[sharedrules.ID242390].Args)
+	if err != nil {
+		return fmt.Errorf("rule option 242445 error: %s", err.Error())
```
Comment (AleksandarSavchev) [inline pkg/provider/virtualgarden/ruleset/disak8sstig/v2r2_ruleset.go:36]:
```suggestion
		return fmt.Errorf("rule option 242390 error: %s", err.Error())
```

File: pkg/provider/virtualgarden/ruleset/disak8sstig/v2r3_ruleset.go [hunk 10]
```diff
@@ -31,6 +31,10 @@ func (r *Ruleset) registerV2R3Rules(ruleOptions map[string]config.RuleOptionsCon
 	if err != nil {
 		return err
 	}
+	opts242390, err := getV2R2OptionOrNil[sharedrules.Options242390](ruleOptions[sharedrules.ID242390].Args)
+	if err != nil {
+		return fmt.Errorf("rule option 242445 error: %s", err.Error())
```
Comment (AleksandarSavchev) [inline pkg/provider/virtualgarden/ruleset/disak8sstig/v2r3_ruleset.go:36]:
```suggestion
		return fmt.Errorf("rule option 242390 error: %s", err.Error())
```

File: pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go [hunk 11]
```diff
@@ -89,7 +121,24 @@ func (r *Rule2000) Run(ctx context.Context) (rule.RuleResult, error) {
...
+			return rule.Result(r, rule.FailedCheckResult("Anonymous authentication is enabled for the kube-apiserver.", configMapTarget)), nil
+		}
+
+		var checkResults []rule.CheckResult
+
+		for _, condition := range authenticationConfig.Anonymous.Conditions {
+			if !slices.ContainsFunc(r.Options.AllowedEndpoints, func(allowedPath AllowedEndpoint) bool {
+				return allowedPath.Path == condition.Path
+			}) {
+				checkResults = append(checkResults, rule.FailedCheckResult(fmt.Sprintf("Anonymous authentication is not allowed for endpoint %s of the kube-apiserver.", condition.Path), configMapTarget))
```
Comment (AleksandarSavchev) [inline pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go:134]:
```suggestion
                                 endpointTarget := configMapTarget.With("details", fmt.Sprintf("endpoint: %s", condition.Path))
				checkResults = append(checkResults, rule.FailedCheckResult("Anonymous authentication is enabled for specific endpoints of the kube-apiserver.", endpointTarget))
```

I think it would be better if we move the specific endpoint to the target in `details`, since we use the message as a key for grouping the findings in the HTML report.

We should also do this for the accepted check.

**Review by AleksandarSavchev — COMMENTED** [review]
Thanks!

File: pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go (hunk 1 above)
Comment (dimityrmirchev) [reply pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go]: Ok, makes sense
