### PR TITLE
[Security Hardened Kubernetes Cluster] Modify Rule 2000 to check for a `default-allow` NetworkPolicy

### LINKED ISSUE #439: [Security Hardened Kubernetes Cluster] Improve rule 2000 to check for `default-allow` policy configured
**What would you like to be added**:
The Security Hardened Kubernetes Cluster rule 2000 should fail for namespaces that have a configured `default-allow` `NetworkPolicy` , since it would override any configured `default-deny` policies in the same namespace.

``` yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow
spec:
  # select all pods in the namespace
  podSelector: {}
  # allow all traffic
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
```

**Why is this needed**:
Configuring a `default-allow` `NetworkPolicy` overrides `default-deny` policies and does not follow the principles of least privilege.

### PR DESCRIPTION
**Pull request by georgibaltiev**
**What this PR does / why we need it**:
Rule 2000 of the `Security Hardened Kubernetes Cluster` ruleset checks to see if unnecessary pod traffic is explicitly disabled for a specific namespace. If a `default-allow` NetworkPolicy is configured, all other NetworkPolicy rules are overwritten by it.

Example `default-allow` NetworkPolicy:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow
spec:
  # select all pods in the namespace
  podSelector: {}
  # allow all traffic
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
```
The modification checks specifically for this type of NetworkPolicy and specifies it in the Failed `CheckResult` Target.

**Which issue(s) this PR fixes**:
Fixes #439 

**Special notes for your reviewer**:
NONE

**Release note**:

```feature user
[Security Hardened Kubernetes Cluster Ruleset] Rule 2000 now explicitly checks for a NetworkPolicy that allows all traffic in a specific namespace
```

### CODE REVIEW

File: pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000.go [hunk 1]
```diff
@@ -94,18 +98,32 @@ func (r *Rule2000) Run(ctx context.Context) (rule.RuleResult, error) {
...
+			if !allowsAllEgress && slices.ContainsFunc(networkPolicy.Spec.Egress, func(egress networkingv1.NetworkPolicyEgressRule) bool {
+				return len(egress.To) == 0 && len(egress.Ports) == 0
+			}) && slices.Contains(networkPolicy.Spec.PolicyTypes, networkingv1.PolicyTypeEgress) {
+				allowsAllEgressTarget = allowsAllEgressTarget.With("kind", "networkPolicy", "name", networkPolicy.Name)
+				allowsAllEgress = true
+			}
+
+			if deniesIngress && deniesEgress || allowsAllIngress && allowsAllEgress {
 				break
 			}
```
Comment (AleksandarSavchev) [inline pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000.go:123]:
```suggestion
			if allowsAllIngress && allowsAllEgress {
				break
			}
```

Let's break only when traffic is allowed, breaking when the traffic is denied might lead us to miss `NetworkPolicy`s that allow traffic.

File: pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000.go [hunk 2]
```diff
@@ -145,7 +167,12 @@ func (r *Rule2000) Run(ctx context.Context) (rule.RuleResult, error) {
 			if accepted {
 				checkResults = append(checkResults, rule.AcceptedCheckResult(msg, acceptedTarget))
 			} else {
-				checkResults = append(checkResults, rule.FailedCheckResult("Egress traffic is not denied by default.", target))
+				if allowsAllEgress {
+					checkResults = append(checkResults, rule.FailedCheckResult("All Egress traffic is allowed by default.", allowsAllEgressTarget))
+				} else {
+					checkResults = append(checkResults, rule.FailedCheckResult("Egress traffic is not denied by default.", target))
+				}
+
```
Comment (AleksandarSavchev) [inline pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000.go:175]:
```suggestion
```

File: pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000_test.go [hunk 3]
```diff
@@ -191,8 +274,8 @@ var _ = Describe("#2000", func() {
 			},
 			{
 				Status:  rule.Failed,
-				Message: "Egress traffic is not denied by default.",
-				Target:  rule.NewTarget("namespace", "kube-system"),
+				Message: "All Egress traffic is allowed by default.",
+				Target:  rule.NewTarget("namespace", "kube-system", "kind", "networkPolicy", "name", "deny-ingress"),
 			},
```
Comment (AleksandarSavchev) [inline pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000_test.go:279]: We should also have a case which returns:
```
Egress traffic is not denied by default.
```

**Review by AleksandarSavchev — CHANGES_REQUESTED** [review]
Thanks!

**Review by AleksandarSavchev — DISMISSED** [review]
/lgtm

File: pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000.go [hunk 4]
```diff
@@ -123,11 +141,15 @@ func (r *Rule2000) Run(ctx context.Context) (rule.RuleResult, error) {
 			if accepted {
 				checkResults = append(checkResults, rule.AcceptedCheckResult(msg, acceptedTarget))
 			} else {
-				checkResults = append(checkResults, rule.FailedCheckResult("Ingress traffic is not denied by default.", target))
+				if allowsAllIngress {
+					checkResults = append(checkResults, rule.FailedCheckResult("All Ingress traffic is allowed by default.", allowsAllIngressTarget))
+				} else {
+					checkResults = append(checkResults, rule.FailedCheckResult("Ingress traffic is not denied by default.", target))
+				}
```
Comment (dimityrmirchev) [inline pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000.go:148]: You can reduce the nesting here by using `else if`

**Review by dimityrmirchev — CHANGES_REQUESTED** [review]
Just one minor nit, other looks good

**Review by dimityrmirchev — APPROVED** [review]
Thanks!

/lgtm
